### PR TITLE
Update map and intro

### PR DESCRIPTION
**Pull request by VnceGd**
It is important to be merging our changes into `dev` more frequently, and `experimental` is getting too large. We also want our branches to be based off of `dev`, so that we do not run into merge conflicts which cause us to lose all progress.

This aims to merge all of our latest changes into `dev` so that future branches will not use `experimental` as a base.

### CODE REVIEW

**Review by DevinD-20 — APPROVED** [review]

**Review by Rosolt — APPROVED** [review]
In my original testing, the game seemed to play completely normally, functioning as expected

**Review by DrAsome — APPROVED** [review]
Seems good to me

**Review by gd387 — COMMENTED** [review]
Looks good

**Review by kadeo13 — COMMENTED** [review]
all good

**Pull request merged**
